language: elixir

otp_release:
  - 20.2
before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - set -e
  - MIX_ENV=test mix format --check-formatted
  - set +e
  - mix coveralls.travis --umbrella
after_script:
  - bash .scripts/inch_report.sh

matrix:
  include:
  - elixir: "1.5.3"
    script:
      - mix coveralls.travis --umbrella
  - elixir: "1.6.2"

branches:
  only:
    - master
    - develop
    - /^feature[\/-].*/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^travis.*/

notifications:
  email:
    recipients:
      - ananya95+travis@gmail.com
