language: elixir
elixir:
  - 1.5.3
  - 1.6.2
otp_release:
  - 20.2
  - 19.3
before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report